src/Entity/Genre.php
<?php

namespace App\Entity;

use App\Repository\GenreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GenreRepository::class)]
class Genre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 50)]
    private $TitreGenre;

    #[ORM\OneToMany(mappedBy: 'Genre', targetEntity: Oeuvre::class)]
    private $oeuvres;

    public function __construct()
    {
        $this->oeuvres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreGenre(): ?string
    {
        return $this->TitreGenre;
    }

    public function setTitreGenre(string $TitreGenre): self
    {
        $this->TitreGenre = $TitreGenre;

        return $this;
    }

    /**
     * @return Collection<int, Oeuvre>
     */
    public function getOeuvres(): Collection
    {
        return $this->oeuvres;
    }

    public function addOeuvre(Oeuvre $oeuvre): self
    {
        if (!$this->oeuvres->contains($oeuvre)) {
            $this->oeuvres[] = $oeuvre;
            $oeuvre->setGenre($this);
        }

        return $this;
    }

    public function removeOeuvre(Oeuvre $oeuvre): self
    {
        if ($this->oeuvres->removeElement($oeuvre)) {
            // set the owning side to null (unless already changed)
            if ($oeuvre->getGenre() === $this) {
                $oeuvre->setGenre(null);
            }
        }

        return $this;
    }
}

src/Entity/Oeuvre.php
<?php

namespace App\Entity;

use App\Repository\OeuvreRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OeuvreRepository::class)]
class Oeuvre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $TitreOeuvre;

    #[ORM\Column(type: 'text')]
    private $Contenu;

    #[ORM\ManyToOne(targetEntity: Genre::class, inversedBy: 'oeuvres')]
    #[ORM\JoinColumn(nullable: false)]
    private $Genre;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'oeuvres')]
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreOeuvre(): ?string
    {
        return $this->TitreOeuvre;
    }

    public function setTitreOeuvre(string $TitreOeuvre): self
    {
        $this->TitreOeuvre = $TitreOeuvre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->Genre;
    }

    public function setGenre(?Genre $Genre): self
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\OeuvreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    // #[Route('/', name: 'home')]
    // public function index(): Response
    // {
    //     $user = $this->getUser();
    //     return $this->render('home/index.html.twig', [
    //         'controller_name' => 'HomeController',
    //         "user" => $user,
    //     ]);
    // }

    #[Route('/api', name: 'homeApi')]
    public function indexApi(): Response
    {
        $user = $this->getUser();
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            "user" => $user,
        ]);
    }

    // #[Route('/oeuvres', name: 'oeuvre')]
    // public function indexOeuvre(OeuvreRepository $oeuvreRepository): Response
    // {
    //     $oeuvres = $oeuvreRepository->findAll();
    //     $user = $this->getUser();
    //     return $this->render('home/indexOeuvre.html.twig', [
    //         "oeuvres" => $oeuvres,
    //         "user" => $user,
    //     ]);
    // }

    #[Route('/api/oeuvres', name: 'oeuvreApi', methods:["GET"])]
    public function indexOeuvreApi(OeuvreRepository $oeuvreRepository): Response
    {
        $oeuvres = $oeuvreRepository->findAll();
        $serializedOeuvres = array_map(function ($se) {
            return array(
                "Id" => $se->getId(),
                 "TitreOeuvre" => $se->getTitreOeuvre(),
                 "Contenu" => $se->getContenu(),
                 "Genre" => $se->getGenre(),
                 "User" => $se->getUser()
              );
            }, $oeuvres);
            return new JsonResponse($serializedOeuvres);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block header %}

{% if user %}
        {% include "./components/header_user.html.twig" %}
        {% else %}
        {% include "./components/header.html.twig"  %}
        {% endif %}
{% endblock %}

{% block content %}

<div class="home">
    <img class="fond" src="{{ asset('images/fond.png') }}" alt="">
    <div class="all-title-home">
        <h1 class="title-home"> Bienvenue sur tous écrivain </h1>
        <span class="sub-title-home"> Une plateforme sociale d'oeuvres en tout genre originale </span>
        <span class="sub-sub-title-home"> Quel est le but ? Cela permet à des auteurs inconnus de publier leurs oeuvres pour les voir apparaître dans de futurs scénarios ou dans le but de les vendre au grand public </span>
    </div>
</div>
{% endblock %}

templates/home/indexOeuvre.html.twig
{% extends 'base.html.twig' %}

{% block header %}

{% if user %}
        {% include "./components/header_user.html.twig" %}
        {% else %}
        {% include "./components/header.html.twig"  %}
        {% endif %}
{% endblock %}

{% block content %}

<div class="containerOeuvre">
    {% for oeuvre in oeuvres %}
    <div class="oeuvre">
        <div> Oeuvre n°{{ oeuvre.id }} </div>
        <div> Genre : {{ oeuvre.genre.titreGenre }} </div>
        <div> Titre : {{ oeuvre.titreOeuvre }} </div>
        <div> {{ oeuvre.contenu }} </div>
    </div>
    {% endfor %}
</div>
{% endblock %}